title: 'Home Cinema'
default_lang: en
author:
  name: 'Joe Bloggs'
  email: joe@example.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Welcome to the Program of Home Cinema, streaming live to you from the Sandberg Graduation Show 2021 at Het Hem.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
